const fs = require('fs-extra');
const path = require('path');
const logger = require('./logger');

class Synthesizer {
  constructor() {
    this.template = `# Test Plan: {title}
Generated by product Tester Autonomous Explorer on {date}

## Scenarios
`;
  }

  synthesize(results) {
    let content = this.template
      .replace('{title}', new URL(results.visitedUrls[0] || 'App').hostname)
      .replace('{date}', new Date().toLocaleString());

    results.flows.forEach((flow, index) => {
      const id = `TC-EXPLORE-${String(index + 1).padStart(2, '0')}`;
      content += `
### ${id}: ${flow.pageType} - ${flow.description}
**URL:** ${flow.url}

#### Steps
`;
      // Convert identified actions to steps
      if (flow.actions && flow.actions.length > 0) {
        flow.actions.forEach((action, stepIdx) => {
          content += `${stepIdx + 1}. ${this.formatAction(action)}\n`;
        });
      } else {
        content += `1. Navigate to ${flow.url}\n2. Verify the page is loaded correctly\n`;
      }

      content += `
#### Expected Result
- The ${flow.pageType} should function as expected during ${flow.description}.
`;
    });

    return content;
  }

  formatAction(action) {
    if (action.action === 'click') return `Click on "${action.element}"`;
    if (action.action === 'fill') return `Enter "${action.value}" into "${action.element}"`;
    return `Perform ${action.action} on ${action.element}`;
  }

  async saveToFile(content, outputPath) {
    await fs.ensureDir(path.dirname(outputPath));
    await fs.writeFile(outputPath, content, 'utf8');
    logger.success(`Test plan synthesized and saved to: ${outputPath}`);
  }
}

module.exports = Synthesizer;
